<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>Projeto - PHP 2019.3</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta charset="utf-8">
  </head>
  <body class="container" style="background-color: #eee;">

    <?php
      if (isset($_SESSION['errors'])) {
        foreach ($_SESSION['errors'] as $error) {
          echo "<div class='alert alert-danger'>{$error}</div>";
        }

        unset($_SESSION['errors']);
      }
    ?>
