<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Ordens de Serviço</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Inicio <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/usuarios">Usuários</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/clientes">Clientes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/chamados">Chamados</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/habilidades">Habilidades</a>
            </li>
        </ul>

        <div class="my-2 my-lg-0">
            <a href="/logout" class="btn btn-danger">Sair</a>
        </div>
    </div>
</nav>