<section class="row mt-5">
  <div class="col-md-12">
    <h1>Dashboard</h1>
  </div>

  <div class="col-md-3 text-white mt-5">
    <div class="bg-primary p-4">
      <span class="h1"><?=$data['users_total']?></span>
      <p class="h5">
        Usuários Cadastrados
      </p>
      <a href="/usuarios" class="btn btn-light">
        Ver com os olhos
      </a>
    </div>
  </div>

  <div class="col-md-3 text-white mt-5">
    <div class="bg-danger p-4">
      <span class="h1"><?=$data['users_inactive']?></span>
      <p class="h5">
        Usuários Inativos
      </p>
      <a href="/usuarios" class="btn btn-light">
        Ver com os olhos
      </a>
    </div>
  </div>

  <div class="col-md-3 text-white mt-5">
    <div class="bg-info p-4">
      <span class="h1"><?=$data['users_attendant']?></span>
      <p class="h5">
        Usuários Atendentes
      </p>
      <a href="/usuarios" class="btn btn-light">
        Ver com os olhos
      </a>
    </div>
  </div>

  <div class="col-md-3 text-white mt-5">
    <div class="bg-dark p-4">
      <span class="h1"><?=$data['users_support']?></span>
      <p class="h5">
        Usuários Técnicos
      </p>
      <a href="/usuarios" class="btn btn-light">
        Ver com os olhos
      </a>
    </div>
  </div>
</section>

<hr class="mt-5">

<section class="row mt-5">
  <div class="col-md-6">
    <div class="card card-body">
      <h3>Últimos usuários cadastrados</h3>
      <table class="table table-hover table-striped mt-3">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Data de Cadastro</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
              <tr>
                <td>Chiquim da Silva</td>
                <td>31/12/2019 09:34:12</td>
                <td><span class="badge badge-success">Ativo</span></td>
              </tr>
              <tr>
                <td>Chiquim da Silva</td>
                <td>31/12/2019 09:34:12</td>
                <td><span class="badge badge-danger">Inativo</span></td>
              </tr>
              <tr>
                <td>Chiquim da Silva</td>
                <td>31/12/2019 09:34:12</td>
                <td><span class="badge badge-success">Ativo</span></td>
              </tr>
              <tr>
                <td>Chiquim da Silva</td>
                <td>31/12/2019 09:34:12</td>
                <td><span class="badge badge-danger">Inativo</span></td>
              </tr>
              <tr>
                <td>Chiquim da Silva</td>
                <td>31/12/2019 09:34:12</td>
                <td><span class="badge badge-success">Ativo</span></td>
              </tr>
              <tr>
                <td>Chiquim da Silva</td>
                <td>31/12/2019 09:34:12</td>
                <td><span class="badge badge-danger">Inativo</span></td>
              </tr>
          </tbody>
      </table>
    </div>
  </div><!-- fecha a col-md-6 -->

  <div class="col-md-6">
    <div class="card card-body">
      <h3>Últimos que nunca logaram</h3>
      <table class="table table-hover table-striped mt-3">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Data de Cadastro</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
              <tr>
                <td>Chiquim da Silva</td>
                <td>31/12/2019 09:34:12</td>
                <td><span class="badge badge-success">Ativo</span></td>
              </tr>
              <tr>
                <td>Chiquim da Silva</td>
                <td>31/12/2019 09:34:12</td>
                <td><span class="badge badge-danger">Inativo</span></td>
              </tr>
              <tr>
                <td>Chiquim da Silva</td>
                <td>31/12/2019 09:34:12</td>
                <td><span class="badge badge-success">Ativo</span></td>
              </tr>
              <tr>
                <td>Chiquim da Silva</td>
                <td>31/12/2019 09:34:12</td>
                <td><span class="badge badge-danger">Inativo</span></td>
              </tr>
              <tr>
                <td>Chiquim da Silva</td>
                <td>31/12/2019 09:34:12</td>
                <td><span class="badge badge-success">Ativo</span></td>
              </tr>
              <tr>
                <td>Chiquim da Silva</td>
                <td>31/12/2019 09:34:12</td>
                <td><span class="badge badge-danger">Inativo</span></td>
              </tr>
          </tbody>
      </table>
    </div><!-- fecha a col-md-6 -->
  </div>
</section>
