<section class="row mt-5">
  <div class="col-md-6"></div>

  <div class="col-md-6 card card-body">
    <h1>Nova Habilidade</h1>

    <hr>

    <form action="" method="post">
      <label for="name">Nome:</label>
      <input id="name" required name="name" class="form-control" placeholder="Digite o nome da habilidade">
      <br>

      <label for="description">Descrição:</label>
      <textarea required id="description" name="description" class="form-control" placeholder="Digite aqui..."></textarea>
      <br>

      <button class="btn btn-primary btn-block">CADASTRAR</button>
      <br>
      <a href="/habilidades" class="btn btn-block btn-sm btn-light">Voltar</a>
    </form>
  </div>
</section>
