<section class="row mt-5">
  <div class="col-md-12 card card-body">
    <h1>Listagem de Habilidades</h1>

    <hr>

    <div class="text-right">
      <a href="/nova-habilidade" class="btn btn-outline-primary">
        Nova Habilidade
      </a>
    </div>

    <table class="table mt-3 table-striped table-hover">
      <thead class="thead-dark">
        <tr>
          <th>Nome</th>
          <th>Descrição</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <?php
            foreach ($data as $skill) {
                echo "
                    <tr>
                        <td>{$skill->getName()}</td>
                        <td>{$skill->getDescription()}</td>
                        <td><a href='/excluir-habilidade?id={$skill->getId()}' class='btn btn-danger'>Excluir</a></td>
                    </tr>
                ";
            }
        ?>
      </tbody>
    </table>
  </div>
</section>
