<section class="row mt-5">
  <div class="col-md-6">FOTO</div>

  <div class="col-md-6 card card-body">
    <h1>Novo Usuário</h1>

    <hr>

    <form action="" method="post">
      <label for="name">Nome: </label>
      <input class="form-control" name="name" id="name" type="name" placeholder="Nome">
      <br>

      <label for="email">Email: </label>
      <input class="form-control" name="email" id="email" type="email" placeholder="Email">
      <br>

      <label for="password">Senha: </label>
      <input class="form-control" name="password" id="password" type="password" placeholder="Senha">
      <br>

      <button class="btn btn-primary btn-block">ENVIAR</button>
    </form>
  </div>
</section>
