<section class="row mt-5">
  <div class="col-md-12 card card-body">
    <h1>Listagem de Usuários</h1>

    <hr>

    <div class="text-right">
      <a href="/novo-usuario" class="btn btn-outline-primary">Novo Usuário</a>
      <a href="/usuarios/pdf" class="btn btn-outline-dark">Gerar PDF</a>
    </div>

    <table class="mt-3 table table-hover table-striped">
      <thead class="thead-dark">
        <tr>
          <th>Nome</th>
          <th>Email</th>
          <th>Tipo</th>
          <th>Status</th>
          <th>Habilidades</th>
          <th>Criado em</th>
          <th>Atualizado em</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
      <?php
        foreach ($data as $user) {
            $status = "<span class='badge badge-success'>Ativo</span>";

            if (!$user->isStatus()) {
                $status = "<span class='badge badge-danger'>Inativo</span>";
            }

            $skills = [];
            foreach ($user->getSkills() as $skill) {
                $skills[] = "<span class='badge badge-info'>{$skill->getName()}</span>";
            }

            $skills = implode(' ', $skills);

            $updatedAt = '---';

            if ($user->getUpdatedAt()) {
                $updatedAt = $user->getUpdatedAt()->format('d/m/Y H:i:s');
            }

            echo "
            <tr>
                <td>{$user->getName()}</td>
                <td>{$user->getEmail()}</td>
                <td>{$user->getType()}</td>
                <td>{$status}</td>
                <td>{$skills}</td>
                <td>{$user->getCreatedAt()->format('d/m/Y H:i:s')}</td>
                <td>{$updatedAt}</td>
                <td>
                <a href='/excluir-usuario?id={$user->getId()}' class='btn btn-danger'>
                    Excluir    
                </a>
                <a href='/editar-usuario?id={$user->getId()}' class='btn btn-warning'>
                    Editar    
                </a>
                </td>
            </tr>
            ";
        }
      ?>
      </tbody>
    </table>
  </div>
</section>
