<section class="row mt-5">
  <div class="col-md-12 card card-body">
    <h1>Listagem de Usuários</h1>

    <hr>

    <div class="text-right">
      <a href="/novo-usuario" class="btn btn-outline-primary">Novo Usuário</a>
    </div>

    <table class="mt-3 table table-hover table-striped">
      <thead class="thead-dark">
        <tr>
          <th>Nome</th>
          <th>Email</th>
          <th>Tipo</th>
          <th>Criado em</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
      <?php
        foreach ($data as $user) {
            echo "
            <tr>
                <td>{$user->getName()}</td>
                <td>{$user->getEmail()}</td>
                <td>{$user->getType()}</td>
                <td>---</td>
                <td>
                <a href='/excluir-usuario?id={$user->getId()}' class='btn btn-danger'>
                    Excluir    
                </a>
                </td>
            </tr>
            ";
        }
      ?>
      </tbody>
    </table>
  </div>
</section>
