<section class="row mt-5">
  <div class="col-md-12 card card-body">
    <h1>Listagem de Usuários</h1>

    <hr>

    <div class="text-right">
      <a href="/novo-usuario" class="btn btn-outline-primary">Novo Usuário</a>
    </div>

    <table class="mt-3 table table-hover table-striped">
      <thead class="thead-dark">
        <tr>
          <th>Nome</th>
          <th>Email</th>
          <th>Telefone</th>
          <th>Status</th>
          <th>Criado em</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Chiquim</td>
          <td>a@a.com</td>
          <td>(85) 9 9999-9999</td>
          <td><span class="badge badge-success">Ativo</span></td>
          <td>01/01/2001 09:09</td>
          <td>
            <a href="#" class="btn btn-warning">Editar</a>
            <a href="#" class="btn btn-danger">Excluir</a>
          </td>
        </tr>
        <tr>
          <td>Chiquim</td>
          <td>a@a.com</td>
          <td>(85) 9 9999-9999</td>
          <td><span class="badge badge-success">Ativo</span></td>
          <td>01/01/2001 09:09</td>
          <td>
            <a href="#" class="btn btn-warning">Editar</a>
            <a href="#" class="btn btn-danger">Excluir</a>
          </td>
        </tr>
        <tr>
          <td>Chiquim</td>
          <td>a@a.com</td>
          <td>(85) 9 9999-9999</td>
          <td><span class="badge badge-success">Ativo</span></td>
          <td>01/01/2001 09:09</td>
          <td>
            <a href="#" class="btn btn-warning">Editar</a>
            <a href="#" class="btn btn-danger">Excluir</a>
          </td>
        </tr>
        <tr>
          <td>Chiquim</td>
          <td>a@a.com</td>
          <td>(85) 9 9999-9999</td>
          <td><span class="badge badge-success">Ativo</span></td>
          <td>01/01/2001 09:09</td>
          <td>
            <a href="#" class="btn btn-warning">Editar</a>
            <a href="#" class="btn btn-danger">Excluir</a>
          </td>
        </tr>
        <tr>
          <td>Chiquim</td>
          <td>a@a.com</td>
          <td>(85) 9 9999-9999</td>
          <td><span class="badge badge-success">Ativo</span></td>
          <td>01/01/2001 09:09</td>
          <td>
            <a href="#" class="btn btn-warning">Editar</a>
            <a href="#" class="btn btn-danger">Excluir</a>
          </td>
        </tr>
        <tr>
          <td>Chiquim</td>
          <td>a@a.com</td>
          <td>(85) 9 9999-9999</td>
          <td><span class="badge badge-success">Ativo</span></td>
          <td>01/01/2001 09:09</td>
          <td>
            <a href="#" class="btn btn-warning">Editar</a>
            <a href="#" class="btn btn-danger">Excluir</a>
          </td>
        </tr>
        <tr>
          <td>Chiquim</td>
          <td>a@a.com</td>
          <td>(85) 9 9999-9999</td>
          <td><span class="badge badge-success">Ativo</span></td>
          <td>01/01/2001 09:09</td>
          <td>
            <a href="#" class="btn btn-warning">Editar</a>
            <a href="#" class="btn btn-danger">Excluir</a>
          </td>
        </tr>
        <tr>
          <td>Chiquim</td>
          <td>a@a.com</td>
          <td>(85) 9 9999-9999</td>
          <td><span class="badge badge-success">Ativo</span></td>
          <td>01/01/2001 09:09</td>
          <td>
            <a href="#" class="btn btn-warning">Editar</a>
            <a href="#" class="btn btn-danger">Excluir</a>
          </td>
        </tr>
        <tr>
          <td>Chiquim</td>
          <td>a@a.com</td>
          <td>(85) 9 9999-9999</td>
          <td><span class="badge badge-success">Ativo</span></td>
          <td>01/01/2001 09:09</td>
          <td>
            <a href="#" class="btn btn-warning">Editar</a>
            <a href="#" class="btn btn-danger">Excluir</a>
          </td>
        </tr>
        <tr>
          <td>Chiquim</td>
          <td>a@a.com</td>
          <td>(85) 9 9999-9999</td>
          <td><span class="badge badge-success">Ativo</span></td>
          <td>01/01/2001 09:09</td>
          <td>
            <a href="#" class="btn btn-warning">Editar</a>
            <a href="#" class="btn btn-danger">Excluir</a>
          </td>
        </tr>
        <tr>
          <td>Chiquim</td>
          <td>a@a.com</td>
          <td>(85) 9 9999-9999</td>
          <td><span class="badge badge-success">Ativo</span></td>
          <td>01/01/2001 09:09</td>
          <td>
            <a href="#" class="btn btn-warning">Editar</a>
            <a href="#" class="btn btn-danger">Excluir</a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</section>
