<section class="row mt-5">
  <div class="col-md-6">
      <img src="" alt="Foto do usuário">

      <br><br>
      <strong>Cadastrado em: </strong> 01/01/2001 09:09<br>
      <strong>Atualizado em: </strong> 01/01/2001 09:09<br>
      <strong>Último login em: </strong> 01/01/2001 09:09<br>
  </div>

  <div class="col-md-6 card card-body">
    <h1>Editar Usuário</h1>

    <hr>
    <form>
      <label for="name">Nome: </label>
      <input id="name" type="text" class="form-control" name="name" placeholder="Nome do usuário">
      <br>

      <label for="email">Email: </label>
      <input id="email" type="email" class="form-control" name="email" placeholder="Email do usuário">
      <br>

      <label for="password">Senha: </label>
      <input id="password" type="password" class="form-control" name="password" placeholder="Minimo de 8 digitos">
      <br>

      <label for="phone">Telefone: </label>
      <input id="phone" type="text" class="form-control" name="phone" placeholder="Telefone do usuário">
      <br>

      <button class="btn btn-primary btn-block">ATUALIZAR</button>
    </form>
  </div>
</section>
