<section class="row mt-5">
    <div class="col-md-6 bg-dark text-white p-5">
      <h1>Bem vindo...</h1>
      <hr class="bg-white">
      <p>
        Uma plataforma diferente, pensada especialmente
        para lhe ajudar a controlar melhor suas ordens debug
        serviço e gerenciar os clientes.
      </p>
    </div>

    <div class="col-md-6">
        <div class="card card-body p-5">
            <form action="" method="post">
                <label for="email">Email: </label>
                <input
                  type="email" name="email"
                  placeholder="Digite o email"
                  class="form-control form-control-lg">

                  <br>

                  <label for="password">Senha: </label>
                  <input
                    type="password" name="password"
                    placeholder="Digite a senha"
                    class="form-control form-control-lg">

                  <br>
                  <button class="btn btn-dark btn-lg btn-block">
                    ENTRAR
                  </button>
            </form>
        </div>
    </div>
</section>
